#!/usr/bin/python3

import sys
import yaml         # have to be installed
import requests     # have to be installed

def exit_program(status_code):
    sys.exit(status_code)

def main():
    # Load configuration
    try:
        config_file = open("owm_exporter.yml", "r")
    except FileNotFoundError:
        print("Configuration file owm_exporter.yml not found! Please read the README.md.")
        exit_program(1)
    except PermissionError:
        print("Configuration file owm_exporter.yml permission denied!")
        exit_program(1)
        
    # Parse configuration file
    config = yaml.safe_load(config_file)

    # URL for API call
    api_url = f"http://api.openweathermap.org/data/2.5/weather?lat={config['lat']}&lon={config['lon']}&appid={config['api_key']}&units={config['measurement']}&lang={config['language']}"

    # Handle API response
    api_response = requests.get(api_url)
    if api_response.status_code == 200:
        api_data = api_response.json()

        # TEST
        #print(api_data)

        # Create output string for the exporter
        exporter_output = f"""HELP owm_lat Latitude of location.
TYPE owm_lat gauge
owm_lat {api_data['coord']['lat']}
HELP owm_lon Longitude of location.
TYPE owm_lon gauge
owm_lon {api_data['coord']['lon']}
HELP owm_weather_main Group of weather parameters (Rain, Snow, Clouds etc.).
TYPE owm_weather_main gauge
owm_weather_main {api_data['weather'][0]['main']}
HELP owm_weather_description Weather condition within the group.
TYPE owm_weather_description gauge
owm_weather_description {api_data['weather'][0]['description']}
"""

        # TEST
        print(exporter_output)
    else:
        print(f"Error with API Request. HTTP code: {api_response.status_code}")
        exit_program(2)

    exit_program(0)

if __name__ == "__main__":
    main()